const colors = {
  light: {
    text: "#000000",
    tint: "#0A84FF",
    background: "#F2F2F7",
    foreground: "#000000",
    card: "#FFFFFF",
    cardForeground: "#000000",
    primary: "#0A84FF",
    primaryForeground: "#FFFFFF",
    secondary: "#F2F2F7",
    secondaryForeground: "#000000",
    muted: "#F2F2F7",
    mutedForeground: "#8E8E93",
    accent: "#E8F4FF",
    accentForeground: "#0A84FF",
    destructive: "#FF3B30",
    destructiveForeground: "#FFFFFF",
    border: "#D1D1D6",
    input: "#D1D1D6",
    success: "#34C759",
    successForeground: "#FFFFFF",
    warning: "#FF9500",
    warningForeground: "#FFFFFF",
    pending: "#AF52DE",
    pendingForeground: "#FFFFFF",
  },
  radius: 10,
};

export default colors;
